const express = require("express");

const app = express();

app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content, Accept, Content-Type, Authorization"
  );
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, DELETE, PATCH, OPTIONS"
  );
  next();
});

app.use("/api/products", (req, res, next) => {
  const products = [
    {
      id: 1,
      title: "iPhone 14 Pro Max",
      price: 1479,
      description: "",
      type: "Téléphone",
      image: "iPhone_14_Pro_Max.jpg.jpg",
      brand: "Apple",
    },
    {
      id: 2,
      title: "iPhone 14 Pro",
      price: 1329,
      description: "",
      type: "Téléphone",
      image: "iPhone_14_Pro_Max.jpg.jpg",
      brand: "Apple",
    },
    {
      id: 3,
      title: "iPhone 14 Plus",
      price: 1119,
      description: "",
      type: "Téléphone",
      image: "1618_edithor_terminaux_636x900_633ed9e642fd7216ac251b53.png",
      brand: "Apple",
    },
    {
      id: 4,
      title: "iPhone 14",
      price: 969,
      description: "",
      type: "Téléphone",
      image: "iPhone_14.jpg",
      brand: "Apple",
    },
    {
      id: 5,
      title: "iPhone 13",
      price: 869,
      description: "",
      type: "Téléphone",
      image: "iPhone_13.png",
      brand: "Apple",
    },
    {
      id: 6,
      title: "iPhone 12",
      price: 809,
      description: "",
      type: "Téléphone",
      image: "iPhone_12.jpg",
      brand: "Apple",
    },
    {
      id: 7,
      title: "iPhone 13 mini",
      price: 769,
      description: "",
      type: "Téléphone",
      image: "iPhone_13_mini.png",
      brand: "Apple",
    },
    {
      id: 8,
      title: "iPhone 12 mini",
      price: 569,
      description: "",
      type: "Téléphone",
      image: "iPhone_12_mini.png",
      brand: "Apple",
    },
    {
      id: 9,
      title: "iPhone 11",
      price: 539,
      description: "",
      type: "Téléphone",
      image: "iPhone_11.png",
      brand: "Apple",
    },
    {
      id: 10,
      title: "Galaxy Z Fold3 5G",
      price: 1799,
      description: "",
      type: "Téléphone",
      image: "Galaxy_Z_Fold3_5G.png",
      brand: "Samsung",
    },
    {
      id: 11,
      title: "Galaxy Z Fold4",
      price: 1799,
      description: "",
      type: "Téléphone",
      image: "Galaxy_Z_Fold4.jpg",
      brand: "Samsung",
    },
    {
      id: 12,
      title: "Galaxy Z Flip4",
      price: 1109,
      description: "",
      type: "Téléphone",
      image: "Galaxy_Z_Flip4.jpg",
      brand: "Samsung",
    },
    {
      id: 13,
      title: "Galaxy S22+",
      price: 1059,
      description: "",
      type: "Téléphone",
      image: "Galaxy_S22+.jpg",
      brand: "Samsung",
    },
    {
      id: 14,
      title: "Galaxy S22",
      price: 859,
      description: "",
      type: "Téléphone",
      image: "Galaxy_S22.jpg",
      brand: "Samsung",
    },
    {
      id: 15,
      title: " Galaxy Z Flip3 5G",
      price: 969,
      description: "",
      type: "Téléphone",
      image: " Galaxy_Z_Flip3_5G.png",
      brand: "Samsung",
    },
    {
      id: 16,
      title: "Galaxy S21 FE 5G",
      price: 759,
      description: "",
      type: "Téléphone",
      image: "Galaxy_S21_FE_5G.jpg",
      brand: "Samsung",
    },
    {
      id: 17,
      title: "Galaxy A13",
      price: 199,
      description: "",
      type: "Téléphone",
      image: "Galaxy_A13.jpg",
      brand: "Samsung",
    },
    {
      id: 18,
      title: "Galaxy S20 FE 5G",
      price: 499,
      description: "",
      type: "Téléphone",
      image: "Galaxy_S20_FE_5G.jpg",
      brand: "Samsung",
    },
    {
      id: 19,
      title: "12 Pro 5G",
      price: 949,
      description: "",
      type: "Téléphone",
      image: "12_Pro_5G.png",
      brand: "Xiaomi",
    },
    {
      id: 20,
      title: "12 5G",
      price: 899,
      description: "",
      type: "Téléphone",
      image: "12_5G.png",
      brand: "Xiaomi",
    },
    {
      id: 21,
      title: "11T Pro 5G",
      price: 599,
      description: "",
      type: "Téléphone",
      image: "11T_Pro_5G.png",
      brand: "Xiaomi",
    },
    {
      id: 22,
      title: "Mi 11i 5G",
      price: 699,
      description: "",
      type: "Téléphone",
      image: "Mi_11i_5G.png",
      brand: "Xiaomi",
    },
    {
      id: 23,
      title: "12T Pro",
      price: 199,
      description: "",
      type: "Téléphone",
      image: "12T_Pro.jpg",
      brand: "Xiaomi",
    },
    {
      id: 24,
      title: "Redmi 10C",
      price: 169,
      description: "",
      type: "Téléphone",
      image: "Redmi_10C.jpg",
      brand: "Xiaomi",
    },
    {
      id: 25,
      title: "Redmi Note 11 Pro 5G",
      price: 369,
      description: "",
      type: "Téléphone",
      image: "Redmi_Note_11_Pro_5G.jpg",
      brand: "Xiaomi",
    },
    {
      id: 26,
      title: "Redmi Note 11S 5G",
      price: 269,
      description: "",
      type: "Téléphone",
      image: "Redmi_Note_11S_5G.jpg",
      brand: "Xiaomi",
    },
    {
      id: 27,
      title: "12T",
      price: 649,
      description: "",
      type: "Ecouteurs",
      image: "12T.jpg",
      brand: "Xiaomi",
    },
  ];
  res.status(200).json(products);
});

module.exports = app;
